### ISSUE TITLE
Incompatibility with SpongeForge

### ISSUE THREAD

**Issue by Aaron1011** [delvr/Farseek#16]
Currently, Farseek [replaces the entire `GameRegistry#generateWorld` method](https://github.com/delvr/Farseek/blob/1.9.4/src/main/scala/farseek/core/FarseekCoreMod.scala#L23). However, the SpongeForge mod needs to be able to apply transformations to that method in order to work properly.

Since Farseek only needs to set a flag before and after invoking the world generator, the current code could be change to modify the existing method, rather than replacing it entirely.

While this is more complex than the current approach, it would allow Farseek to be compatible with SpongeForge, which would be greatly appreciated.

**Comment by Towsty** [comment]
Would love to see this patched at some point.

**Comment by Towsty** [comment]
I would love to see this addressed

**Comment by delvr** [comment]
This is being worked on - the method conflict being reported is not too hard to fix but the mods still crash because of a deeper problem. That is, Streams needs to create a copy of the world chunk generator for look-ahead purposes and does so by calling `worldProvider.createChunkGenerator()`, but Sponge has its own complex mechanism for creating its custom generator which I can't easily hook into. I'll look into it so more and possibly enlist the help of the Sponge devs and see if we can meet in the middle.

**Comment by SmallSansSerif** [comment]
Has there been any more progress on this? What's the ETA for a fix?

**Comment by delvr** [comment]
Sorry I dropped the ball on this one - I'll couldn't figure out a solution back then but I'll take another look.

**Comment by Aaron1011** [comment]
@delvr: Ok. Feel free to come on `#spongedev` on EsperNet if you have any questions about how to best  change this for Sponge compatibility.

**Comment by delvr** [comment]
Good news! This is now fixed in dev and will be included in an upcoming bug-fix release in a few days.

**Comment by delvr** [comment]
The conflicting method patch is fixed in Farseek 2.0. Then with some other Sponge-specific ChunkProvider initialization workarounds I made the new Streams 0.3 compatible with SpongeForge.

(My other Farseek-based mod Repose however, is _not_ Sponge-compatible and is unlikely to be in the near future, since the patch conflicts run too deep in that one).

Please give Streams 0.3/Farseek 2.0 a try and let me know of any issues, thanks!

**Comment by StarrDraws** [comment]
http://pastebin.com/9anvKm5S
Tried putting Streams + Farseek on my Sponge server today. Loved playing it on single player, was hoping to have it on the family server. I have no crash on the server when I take both off again.

MC: 1.11.2
Sponge: 6.0.0-BETA-2200
Forge: 1.11.2-2227
Streams: 1.11-0.3
Farseek: 1.11-2.1

**Comment by simon816** [comment]
@TheSilentSong 
> [17:33:49] [main/ERROR] [FML/]: Unable to read the jar file Aquaculture-1.11.2-1.5.0.33.jar - ignoring
java.util.zip.ZipException: **error in opening zip file**

The file "Aquaculture-1.11.2-1.5.0.33.jar" is corrupt, redownload it.

**Comment by StarrDraws** [comment]
...did that and also redownloaded these two mods, that did the trick. *facepalm*
Never seen those errors before so didn't know how to fix it.

**Comment by ghost** [comment]
This is still happening in 1.10.2, world runs once then farseek says you need to run /fml confirm and if you do it corrupts the world.

**Comment by Rongmario** [comment]
Can we bump? On 1.10 still broke.

**Comment by delvr** [comment]
Sorry for the delay - been busy moving to a new city. :) I'll take a look at this soon.

**Comment by Rongmario** [comment]
No problem!

**Comment by JonoColwell** [comment]
Is this still on the roadmap?

**Comment by delvr** [comment]
Yes - I've tested with Sponge-1.10.2-2281-5.2.0-BETA-2401 and was able to generate a river in a new server world (seed -6229945911322748028, coords -233 64 423), so that part works. As for the server warning on existing Streams world, it's a false alarm due to how Sponge loads dimensions and I have an upcoming patch that fixes that. I have not been able to reproduce the world corruption described by @Astralick however - can I get more details on that?

**Comment by vannucci16** [comment]
I am having this issue after adding the latest sponge forge to the Atlauncher Homestead

https://pastebin.com/2JD1JipU

but works fine with out farseek and steams

**Comment by vannucci16** [comment]
I am having this issue after adding sponge forge to the modpack homestead removing Farseek and steams fixes it
https://pastebin.com/2JD1JipU

**Comment by delvr** [comment]
Hi vannucci16, could you retry with the latest version of Sponge (1.10.2-2477-5.2.0-BETA-2731)? And if it still crashes, could you try removing all mods except Farseek, Streams and Sponge and then re-adding the mods listed in the "coremods" section at the top of the crash report one by one to see when it starts crashing? Thanks!

**Comment by Xplodin** [comment]
Having this issue on latest spongeforge and farseek/streams

**Comment by SkyLicks** [comment]
Having this issue again in the latest version of spongeforge and farseek.

**Comment by DragaoNimhe** [comment]
I'm also having this issue; all the way from the latest version of spongeforge back to 7.1.9. I've tried both versions 2.5 and 2.5.1 of farseek; reported by sponge to work, without success. I'm running a Hexxit II server if that info helps!

**Comment by DragaoNimhe** [comment]
Update:
After nearly 24 hours of testing I've found the issues for you!
In the Hexxit II modpack there are 2 (technically 3) issues causing the boot error with Farseek/Streams to re-present.
- randompatches mod (version 1.22.1.10)
- chunkgenlimiter (version 1.1)
      - chunkgenlimiter CORE (installed when original mod is run)
      
Disabling these mods fixed the issue completely. Passing this on because you're such a wonderful active dev; hopefully this will help you guide others that come to you with the same issue! <3

**Comment by SkyLicks** [comment]
Personally, I was on the enigmatica 2 lite pack. I was using the latest version of 1.12.2. For me removing farseek and streams fix the issue and I was able to boot up the pack with sponge forge.
